version: "3.9"

services:
  # ---------------- PostgreSQL Database ----------------
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: phishingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  # ---------------- Phishing Detection Service ----------------
  phishing:
    build:
      context: ../phishing-service
    container_name: phishing_service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:1234@postgres:5432/phishingdb   # fix: use service name postgres
      - FLASK_ENV=development
      - PHISHING_ALERT_API_KEY=super_secret_123
      - SCORE_BUMP_FACTOR=0.15
      - ALERT_TTL_HOURS=24
    ports:
      - "5000:5000"
    volumes:
      - ../phishing-service:/app
    restart: always
    networks:
      - app-net

  # ---------------- DNS Tunneling Detection Service ----------------
  dns_tunnel:
    build:
      context: ../dns-tunnel-service
    container_name: dns_tunnel_service
    depends_on:
      - phishing
    environment:
      - PHISHING_SERVICE_URL=http://phishing:5000/api/phishing_alert     # fix: use service name phishing
      - PHISHING_ALERT_API_KEY=super_secret_123
      - ALERT_THRESHOLD=0.6
    ports:
      - "8053:8053"
    volumes:
      - ../dns-tunnel-service:/app
    restart: always
    networks:
      - app-net

# ---------------- Shared Docker Network ----------------
networks:
  app-net:
    driver: bridge

# ---------------- Persistent PostgreSQL Storage ----------------
volumes:
  postgres_data:
